x = input('Digite um valor: ')
print(f'O tipo primtivo desse valor é: {type(x)}')
print(f'Esse valor é alfanumérico? {x.isalnum()}')
print(f'Esse valor só tem espaços? {x.isspace()}')
print(f'Esse valor é numérico? {x.isnumeric()}')
print(f'Esse valor é alfabético? {x.isalpha()}')
print(f'Esse valor está em maiúsculas? {x.isupper()}')
print(f'Esse valor está em minúsculas? {x.islower()}')
print(f'Esse valor está capitalizado? {x.istitle()}')