x = input('Type one value: ')
print(f'The primitive type of this value is: {type(x)}')
print(f'This value is alphanumeric? {x.isalnum()}')
print(f'This value has only spaces? {x.isspace()}')
print(f'This value is numeric? {x.isnumeric()}')
print(f'This value is alphabetic? {x.isalpha()}')
print(f'This value is upper? {x.isupper()}')
print(f'This value is lower? {x.islower()}')
print(f'This value is captalized? {x.istitle()}')