nome = str(input('Digite seu nome completo: ')).strip()
upper = nome.upper()
lower = nome.lower()
length = len(nome) - nome.count(' ')
length_1 = nome.split()
length_2 = len(length_1[0])
print(f'Seu nome em maiúsculas é: {upper};')
print(f'Seu nome em minúsculas é: {lower};')
print(f'Seu nome tem ao todo {length} letras;')
print(f'Seu primeiro nome tem {length_2} letras.')